### ISSUE TITLE
Error when load the spade model

### ISSUE THREAD

**Issue by howardgriffin** [harlanhong/CVPR2022-DaGAN#4]
Nice work!
But I have encountered a problem that when I load the SPADE model as I load theDaGAN model, the following problem occurs. Any suggestions?
```Traceback (most recent call last):
  File "demo.py", line 191, in <module>
    generator, kp_detector = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint, cpu=opt.cpu)
  File "demo.py", line 46, in load_checkpoints
    generator.load_state_dict(ckp_generator)
  File "/root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DepthAwareGenerator:
   Missing key(s) in state_dict: "up_blocks.0.conv.weight", "up_blocks.0.conv.bias",...... "final.bias". 
   Unexpected key(s) in state_dict: "decoder.compress.weight", "decoder.compress.bias", ..."decoder.G_middle_0.norm_0.mlp_beta.weight" ```
Any suggestions?

**Comment by harlanhong** [comment]
Hi, @howardgriffin 

You should use the SPADEDepthAwareGenerator instead of the DepthAwareGenerator when you load the SPADE model. Thanks.

**Comment by howardgriffin** [comment]
Got it! Thank you.
