### ISSUE TITLE
Missing file or dependancy

### ISSUE THREAD

**Issue by LeoLovechest** [harlanhong/CVPR2022-DaGAN#56]
Getting this not sure what I'm doing wrong 
```
(base) leo@leo:~/CVPR2022-DaGAN$ CUDA_VISIBLE_DEVICES=0 python demo.py  --config config/vox-adv-256.yaml --driving_video Home/CVPR2022-DaGAN --source_image Home/CVPR2022-DaGAN --checkpoint Home/CVPR2022-DaGAN --relative --adapt_scale --kp_num 15 --generator DepthAwareGenerator 
Traceback (most recent call last):
  File "/home/leo/anaconda3/lib/python3.9/site-packages/torch-1.13.1-py3.9-linux-x86_64.egg/torch/__init__.py", line 172, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/leo/anaconda3/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcublas.so.11: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/leo/CVPR2022-DaGAN/demo.py", line 7, in <module>
    import modules.generator as GEN
  File "/home/leo/CVPR2022-DaGAN/modules/generator.py", line 1, in <module>
    import torch
  File "/home/leo/anaconda3/lib/python3.9/site-packages/torch-1.13.1-py3.9-linux-x86_64.egg/torch/__init__.py", line 217, in <module>
    _load_global_deps()
  File "/home/leo/anaconda3/lib/python3.9/site-packages/torch-1.13.1-py3.9-linux-x86_64.egg/torch/__init__.py", line 178, in _load_global_deps
    _preload_cuda_deps()
  File "/home/leo/anaconda3/lib/python3.9/site-packages/torch-1.13.1-py3.9-linux-x86_64.egg/torch/__init__.py", line 158, in _preload_cuda_deps
    ctypes.CDLL(cublas_path)
  File "/home/leo/anaconda3/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/leo/anaconda3/lib/python3.9/site-packages/nvidia_cuda_runtime_cu11-11.7.99-py3.9-linux-x86_64.egg/nvidia/cublas/lib/libcublas.so.11: cannot open shared object file: No such file or directory
```

**Comment by harlanhong** [comment]
That is caused by your environment. You can try to install the PyTorch of version '1.9.0+cu111'.

**Comment by LeoLovechest** [comment]
> That is caused by your environment. You can try to install the PyTorch of version '1.9.0+cu111'.

Installing that version seems to remove my torch vision as I used 
`pip install torch==1.9.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html`

Stupidly I did a `pip install torchvision` soon after due to n_o module name torchvision_ error which changed the version back to my original issue, what is the correct command here?
`
pip install torch==1.9.0+cu111 torchvision==?.?.?+cu111 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by harlanhong** [comment]
> > That is caused by your environment. You can try to install the PyTorch of version '1.9.0+cu111'.
> 
> Installing that version seems to remove my torch vision as I used `pip install torch==1.9.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html`
> 
> Stupidly I did a `pip install torchvision` soon after due to _no module name torchvision_ error which changed the version back to my original issue, what is the correct command here? ` pip install torch==1.9.0+cu111 torchvision==?.?.?+cu111 -f https://download.pytorch.org/whl/torch_stable.html`

It should be "'0.10.0+cu111'".  You're better off downloading the wheel file.
